---
abstract: 'Catalyst plugin to turn on '
author:
  - 'John Goulah       <jgoulah@cpan.org>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Config::General: 0
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-DebugCookie
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7007
  Class::C3: 0.19
  Digest::MD5: 0
  Sub::Exporter: 0
  perl: 5.8.1
tests: t/*.t
version: 0.999001
